### ISSUE TITLE
Building the vector database

### ISSUE THREAD

**Issue by rodja** [mggger/gpt-nicegui#2]
Could you include the code which generates the vector database? In NiceGUI we use a script to [build the search index](https://github.com/zauberzeug/nicegui/blob/main/website/build_search_index.py). Maybe there are synergies...

**Comment by rodja** [comment]
Maybe we could integrate the code to build the Chroma database into the main NiceGUI repository. That would allow other projects to also use it. For example a ChatGPT plugin...

**Comment by mggger** [comment]
@rodja  

Got it, the code for building embeddings has been uploaded. 

Yeah, the idea of scanning documents is inspired by this script [build the search index](https://github.com/zauberzeug/nicegui/blob/main/website/build_search_index.py)

**Comment by rodja** [comment]
Thanks. I'll have a look at it in the next days.
